version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./doc-root:/var/www/html/
    ports:
      - 8080:80
  custom-php-apache-environment:
    build: .
    image: custom-php
    volumes:
      - ./doc-root:/var/www/html/
    ports:
      - 8090:80